services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HTB_TOKEN=${HTB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app

  kali:
    build:
      context: ./kali  
      dockerfile: Dockerfile
    container_name: kali
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"  

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"